### ISSUE TITLE
Use env vars in import ref

### ISSUE THREAD

**Issue by crazy-max** [travis-ci/travis-yml#169]
Hi,

I'm using the build configuration import for a while now and I wanted to test something.
I tried to import configuration with an environment variable as an import ref but it [doesn't seem to work](https://travis-ci.com/github/portapps/kitty-portable/requests?requestId=331727978) (`File portapps/portapps:.travis/configs/install.yml not found on GitHub`):

```yml
version: ~> 1.0

os: windows
language: shell

before_install:
  - export PORTAPPS_VERSION=$(cat go.mod | grep github.com/portapps/portapps | awk '{print $2}')

import:
  - portapps/portapps:.travis/configs/install.yml@$PORTAPPS_VERSION
  - portapps/portapps:.travis/configs/build.yml@$PORTAPPS_VERSION
  - portapps/portapps:.travis/configs/set-version.yml@$PORTAPPS_VERSION
  - portapps/portapps:.travis/configs/git-config.yml@$PORTAPPS_VERSION
  - portapps/portapps:.travis/configs/deploy.yml@$PORTAPPS_VERSION
  - portapps/portapps:.travis/configs/notifs.yml@$PORTAPPS_VERSION
```

Is there a way to do this?

Thanks!
