### ISSUE TITLE
This configuration is not expanded into matrix

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-yml#19]
Consider recent builds of https://travis-ci.org/travis-ci/travis-rubies/builds/:

1. https://travis-ci.org/travis-ci/travis-rubies/builds/333889961
1. https://travis-ci.org/travis-ci/travis-rubies/builds/333890308
1. https://travis-ci.org/travis-ci/travis-rubies/builds/333890391
1. https://travis-ci.org/travis-ci/travis-rubies/builds/333890538

These builds should define build matrices, like so (in the corresponding order):
1. https://travis-ci.org/travis-ci/travis-rubies/builds/333573415
1. https://travis-ci.org/travis-ci/travis-rubies/builds/333573654
1. https://travis-ci.org/travis-ci/travis-rubies/builds/333573568
1. https://travis-ci.org/travis-ci/travis-rubies/builds/333573266

But the former builds have only one job (and it is default), or failed to run the build for some reason.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-rubies/blob/72bf25a562dbd0a05c0b4d4c44d4aab960e174ec/.travis.yml

```yaml
language: c

script:
- unset JRUBY_OPTS
- ./build.sh

cache: ccache

matrix:
  include:
  - os: linux
    sudo: required
    dist: precise
    group: edge
    before_script: "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"
  - os: linux
    before_script:
      - 'echo -e "gem-wrappers\nrubygems-bundler\nbundler\nrake\nrvm\n" >> ~/.rvm/gemsets/global.gems'
      - "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"
      - "sudo apt-get install haveged"
      - "sudo service haveged start"
    services: docker
  - os: linux
    dist: xenial
    language: generic
    before_script:
      - 'echo -e "gem-wrappers\nrubygems-bundler\nbundler\nrake\nrvm\n" >> ~/.rvm/gemsets/global.gems'
      - "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"
      - "sudo apt-get install haveged"
      - "sudo service haveged start"
  - os: osx
    before_install: sw_vers
    osx_image: xcode6.4
  - os: osx
    before_install: sw_vers
    osx_image: xcode7.2
  - os: osx
    before_install: sw_vers
    osx_image: xcode8.1

after_failure: find $rvm_path/log/ -type f | xargs ls -t | head -n 1 | xargs cat

notifications:
  email: false
```
