### ISSUE TITLE
Arabic text gets gobbled up

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-yml#190]
Given:
```yaml
language: python
script:
  - cat ضروریاں.txt
```

`travis-yml` returns:

```
{
  "language": "python",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "script": [
    "cat .txt"
  ],
}
```
