### ISSUE TITLE
"Camelcase" warning is picking up only the hyphenated keys

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-yml#27]
# Problem

This snippet with a hyphenated key

```yaml
deploy:
  skip-cleanup: true
  ⋮
```

results in warning:

> key `skip-cleanup` is camelcased, using `skip_cleanup`

while a real camel cased key

```yaml
deploy:
  SkipCleanup: true
  ⋮
```

is silently ignored.

The message should read "X is hyphenated; using X snake_cased".

(Incidentally, I don't recall we ever supported camel cased keys.)
