### ISSUE TITLE
Add support for top-level "arch"

### ISSUE THREAD

**Issue by meatballhat** [travis-ci/travis-yml#38]
Near-future work on hosted Travis and some current work on at least one Travis Enterprise installation is raising the topic of supporting the concept of architecture, designated via an `arch` top-level key, e.g.:

``` yaml
language: ruby
os: linux
arch: x86_64
```

``` yaml
language: python
os: linux
arch:
- amd64
- arm64
- ppc64
```

Valid values, at the time of this writing, are:

- `x86_64` / `amd64` (currently supported)
- `ppc64` / `ppc64le` (currently supported in closed beta)
- `arm64` (proposed future)
