### ISSUE TITLE
Do not pick the first value from matrix expansion keys into listed jobs

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-yml#46]
With this config:

```
          env:
            global:
              - FOO=bar
            matrix:
              - BAR=foo
              - BAR=baz
          matrix:
            include:
              - stage: foo
                if: env(BAR) = foo
              - stage: bar
                if: env(BAR) = bar
```

Gatekeeper currently creates jobs with these configs:

```
{:env=>"BAR=foo", :global_env=>["FOO=bar"], :language=>"ruby", :group=>"stable", :dist=>"trusty", :os=>"linux"}
{:env=>"BAR=baz", :global_env=>["FOO=bar"], :language=>"ruby", :group=>"stable", :dist=>"trusty", :os=>"linux"}
{:env=>"BAR=foo", :global_env=>["FOO=bar"], :language=>"ruby", :group=>"stable", :dist=>"trusty", :if=>"env(BAR) = foo", :stage=>"foo", :os=>"linux"}
```

In the last one, which was generated out of `matrix.include` it should not have `:env=>"BAR=foo"` set. 

I believe for all matrix expansion keys Gatekeeper currently picks the first element out of an array, unless the key is already given on the job. @BanzaiMan and i think we should stop doing that in `travis-yml`.
