### ISSUE TITLE
Travis does't recognize branches with slash

### ISSUE THREAD

**Issue by barreeeiroo** [travis-ci/travis-yml#66]
I have this piece of code in my travis.yml file:

```
deploy:
  provider: script
  script: bash $TRAVIS_BUILD_DIR/deploy-to-gae.sh
  on: 
    branch: Makeroid/BETA
  skip_cleanup: true
```

However, the deploy script is not being executed in that branch. Travis returns this:

![image](https://user-images.githubusercontent.com/19251112/44100798-1f75217a-9fe6-11e8-91b1-665a55dbf7c0.png)
