### ISSUE TITLE
[warning] in matrix.include section: unexpected key `name`

### ISSUE THREAD

**Issue by joaomlneto** [travis-ci/travis-yml#68]
For a given input:

```yml
language: minimal
matrix:
  include:
    - name: "one"
      env: MATRIX_ENV=1
    - name: "two"
      env: MATRIX_ENV=2
```

`$ travis lint` outputs:

```
Warnings for .travis.yml:
[x] in matrix.include section: unexpected key name, dropping
```

This is valid ([and works](https://travis-ci.com/joaomlneto/clang-tidbit)) as per the [documentation](https://docs.travis-ci.com/user/customizing-the-build/#naming-jobs-within-matrices). No warning should be generated.
