### ISSUE TITLE
Support matrix expansion for Nix

### ISSUE THREAD

**Issue by joepvd** [travis-ci/travis-yml#69]
The following should result in a matrix of 3 items:

```yaml
language: nix
nix:
- 1.2.3
- 2.3.4
- 3.4.5
```

cf. 
https://github.com/travis-ci/travis-gatekeeper/pull/374
https://github.com/travis-ci/travis-build/pull/1455
https://github.com/travis-pro/team-build-env/issues/55
