### ISSUE TITLE
Parsing Yaml-Like Bash Strings

### ISSUE THREAD

**Issue by ax3l** [travis-ci/travis-yml#8]
The current "live" parser on org and the [linter](http://lint.travis-ci.org/) can not parse files containing strings such as:

```yaml
language: cpp
sudo: false
dist: trusty

install:
- echo -e "config:\n  build_jobs: 2"
```

But allow the modified versions
```yaml
install:
- echo -e "config:\n  build_jobs:"" 2"
```

and
```yaml
install:
- |
  echo -e "config:\n  build_jobs: 2"
```
.

Maybe you want to add such a yaml file to your test coverage for the new parser? Unfortunately I am an absolute ruby novice and can not provide a PR :)
